public class conditional {
    public static void main(String[] args){
        int x = 8;
        int y = 10;
        if(!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            (x>y || y>x)){
            System.out.println("Hello");
        }
        else{
            System.out.println("Bye");
        }
    }
    
}
